import { Inter } from "next/font/google";
import "./globals.css";
import MyFooter from "@/components/component/footer";
import Navbar from "@/components/component/navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <MyFooter />
      </body>
    </html>
  );
}
