/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PxG4CvUBjl6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function Component() {
  return (
    <div className="flex justify-center items-center ">
      <Tabs className="w-full max-w-2xl" defaultValue="about">
        <TabsList className="flex w-full justify-center border-b">
          <TabsTrigger value="about">Description</TabsTrigger>
          <TabsTrigger value="features">Sujets</TabsTrigger>
          <TabsTrigger value="contact">Modèle</TabsTrigger>
        </TabsList>
        <TabsContent className="p-6" value="about">
          <p className="mt-4 text-gray-500 dark:text-gray-400 text-justify">
            Les Journées des Sciences de l'Ingénieur et de l'Intelligence
            Artificielle (JSIIA) sont un événement exceptionnel réunissant des
            experts, des chercheurs, des professionnels et des passionnés du
            domaine de l'ingénierie et de l'intelligence artificielle. Cet
            événement offre une plateforme dynamique pour l'échange d'idées, la
            présentation de recherches innovantes et la discussion sur les
            avancées les plus récentes dans ces domaines en constante évolution.
            Lors de ces journées, les participants auront l'opportunité
            d'assister à des conférences données par des experts renommés,
            d'assister à des ateliers interactifs et de participer à des
            sessions de discussion sur des sujets variés liés à l'ingénierie et
            à l'intelligence artificielle. Les présentations couvriront un large
            éventail de thèmes, notamment la robotique, l'apprentissage
            automatique, la vision par ordinateur, les systèmes intelligents,
            les réseaux neuronaux, la cybersécurité, et bien d'autres encore.
            Les JSIIA offrent également une excellente opportunité de
            réseautage, permettant aux participants d'établir des contacts avec
            d'autres professionnels du secteur, de discuter des dernières
            tendances et de découvrir de nouvelles collaborations potentielles.
            Que vous soyez un chercheur, un étudiant, un ingénieur ou un
            entrepreneur, les Journées des Sciences de l'Ingénieur et de
            l'Intelligence Artificielle sont un événement incontournable pour
            rester à la pointe de l'innovation et de la technologie.
          </p>
        </TabsContent>
        <TabsContent className="p-6" value="features">
          <ul className="mt-4 space-y-2 text-gray-500 dark:text-gray-400 text-justify">
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Robotique et Automatisation
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Apprentissage Automatique et Intelligence Artificielle
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Systèmes Intelligents et Internet des Objets (IoT)
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Vision par Ordinateur et Traitement d’Images
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Ingénierie des Données et Analyse Prédictive
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Systèmes de Contrôle et Intelligence Artificielle
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Cybersécurité et Protection des Données
            </li>
            <li>
              <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
              Biological Modeling and Disease Prediction
            </li>
          </ul>
        </TabsContent>
        <TabsContent className="p-6" value="contact">
          <p className="mt-4 text-gray-500 dark:text-gray-400 text-justify">
            Pour vous aider à préparer votre soumission, veuillez télécharger
            notre modèle de document de conférence ci-dessous. Ce modèle fournit
            des directives et une structure pour la préparation de votre
            proposition, assurant ainsi une uniformité et une cohérence dans les
            soumissions. Veuillez consulter attentivement les instructions
            incluses dans le modèle avant de soumettre votre proposition.
          </p>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
